import type { StoreData } from "./types";

const now = "2026-09-06T12:00:00.000Z";

export const DEMO_PASSWORD = "vestry";

export function createSeed(): StoreData {
  return {
    churchName: "Harbor Church",
    orgType: "church",
    modules: ["calendar", "people", "scheduling", "events", "worship"],
    users: [
      {
        id: "user-elena",
        email: "director@harbor.church",
        name: "Elena Ward",
        role: "director",
        password: DEMO_PASSWORD,
      },
      {
        id: "user-jordan",
        email: "member@harbor.church",
        name: "Jordan Ellis",
        role: "member",
        password: DEMO_PASSWORD,
      },
    ],
    people: [
      {
        id: "person-elena",
        name: "Elena Ward",
        email: "director@harbor.church",
        defaultPosition: "Worship Leader",
        userId: "user-elena",
      },
      {
        id: "person-jordan",
        name: "Jordan Ellis",
        email: "member@harbor.church",
        defaultPosition: "Vocals",
        userId: "user-jordan",
      },
      {
        id: "person-micah",
        name: "Micah Chen",
        email: "micah@harbor.church",
        defaultPosition: "Acoustic Guitar",
      },
      {
        id: "person-priya",
        name: "Priya Shah",
        email: "priya@harbor.church",
        defaultPosition: "Keys",
      },
      {
        id: "person-sam",
        name: "Sam Okonkwo",
        email: "sam@harbor.church",
        defaultPosition: "Drums",
      },
      {
        id: "person-naomi",
        name: "Naomi Brooks",
        email: "naomi@harbor.church",
        defaultPosition: "Vocals",
      },
      {
        id: "person-caleb",
        name: "Caleb Ruiz",
        email: "caleb@harbor.church",
        defaultPosition: "Bass",
      },
    ],
    songs: [
      {
        id: "song-goodness",
        title: "Goodness of God",
        artist: "Bethel Music / Jenn Johnson",
        key: "G",
        tempo: 126,
        notes: "Start sparse, build on chorus 2. Hold the last chorus.",
        youtubeUrl: "https://www.youtube.com/watch?v=IvSuGyJQ6oM",
        audioFilename: "harbor-rehearsal.wav",
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-how-great",
        title: "How Great Is Our God",
        artist: "Chris Tomlin",
        key: "C",
        tempo: 78,
        notes: "Capo 3 for acoustic if needed. Walk-up into the bridge.",
        youtubeUrl: "https://www.youtube.com/watch?v=XV4nOVmWW2A",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-10000",
        title: "10,000 Reasons (Bless the Lord)",
        artist: "Matt Redman",
        key: "G",
        tempo: 73,
        notes: "Easy congregational opener. Keep drums light until chorus.",
        youtubeUrl: "https://www.youtube.com/watch?v=DXDGE_lRI0E",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-beautiful-name",
        title: "What A Beautiful Name",
        artist: "Hillsong Worship",
        key: "D",
        tempo: 68,
        notes: "Watch the drop before the second chorus. Keys lead the pad.",
        youtubeUrl: "https://www.youtube.com/watch?v=r5L71QnFmPQ",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-great-are-you",
        title: "Great Are You Lord",
        artist: "All Sons & Daughters",
        key: "A",
        tempo: 72,
        notes: "Breathing room after the instrumental. No click on the last chorus.",
        youtubeUrl: "https://www.youtube.com/watch?v=uHz0w-HG4iw",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-holy-forever",
        title: "Holy Forever",
        artist: "Bethel Music / Chris Tomlin",
        key: "Db",
        tempo: 72,
        notes: "Big unison on the bridge. Leave space for the room.",
        youtubeUrl: "https://www.youtube.com/watch?v=oOXvQz_gtfA",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-build-my-life",
        title: "Build My Life",
        artist: "Housefires / Pat Barrett",
        key: "E",
        tempo: 70,
        notes: "Acoustic-led verse. Band in on chorus.",
        youtubeUrl: "https://www.youtube.com/watch?v=QdK6vS9jJPY",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-king-of-kings",
        title: "King of Kings",
        artist: "Hillsong Worship",
        key: "D",
        tempo: 68,
        notes: "Narrative verses — keep dynamics honest.",
        youtubeUrl: "",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-blessing",
        title: "The Blessing",
        artist: "Kari Jobe / Cody Carnes",
        key: "B",
        tempo: 70,
        notes: "Benediction slot. Harmony stack on the amen section.",
        youtubeUrl: "",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-yet-not-i",
        title: "Yet Not I But Through Christ In Me",
        artist: "CityAlight",
        key: "C",
        tempo: 76,
        notes: "Congregation knows this. Let them sing.",
        youtubeUrl: "https://www.youtube.com/watch?v=hwc2d1Xt8gM",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-fount",
        title: "Come Thou Fount",
        artist: "Traditional",
        key: "D",
        tempo: 84,
        notes: "Arrangement: folk, 6/8 feel. No tracks.",
        youtubeUrl: "",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "song-doxology",
        title: "Doxology",
        artist: "Traditional",
        key: "G",
        tempo: 80,
        notes: "A cappella option after the offering.",
        youtubeUrl: "",
        audioFilename: null,
        createdAt: now,
        updatedAt: now,
      },
    ],
    plans: [
      {
        id: "plan-sep-13",
        name: "Sunday Gathering",
        date: "2026-09-13",
        serviceTime: "10:00 AM",
        notes: "First fall series. Keep the room warm — less production, more voice.",
        createdAt: now,
        items: [
          {
            id: "item-13-call",
            type: "notes",
            title: "Call to worship",
            body: "Psalm 100. Elena reads; band holds a G pad underneath.",
          },
          {
            id: "item-13-how-great",
            type: "song",
            title: "How Great Is Our God",
            songId: "song-how-great",
          },
          {
            id: "item-13-goodness",
            type: "song",
            title: "Goodness of God",
            songId: "song-goodness",
          },
          {
            id: "item-13-welcome",
            type: "announcement",
            title: "Welcome & peace",
            body: "Welcome guests. Mention Thursday rehearsal dinner after practice.",
          },
          {
            id: "item-13-holy",
            type: "song",
            title: "Holy Forever",
            songId: "song-holy-forever",
          },
          {
            id: "item-13-sermon",
            type: "sermon",
            title: "The God who keeps",
            body: "Psalm 121. Pastor Mara. ~28 minutes. Band seated, no underscore.",
          },
          {
            id: "item-13-response",
            type: "youtube",
            title: "Response — Holy Forever (rehearsal cut)",
            youtubeUrl: "https://www.youtube.com/watch?v=oOXvQz_gtfA",
          },
          {
            id: "item-13-blessing",
            type: "song",
            title: "The Blessing",
            songId: "song-blessing",
          },
        ],
        assignments: [
          { id: "as-13-elena", personId: "person-elena", position: "Worship Leader", status: "accepted" },
          { id: "as-13-jordan", personId: "person-jordan", position: "Vocals", status: "pending" },
          { id: "as-13-micah", personId: "person-micah", position: "Acoustic Guitar", status: "accepted" },
          { id: "as-13-priya", personId: "person-priya", position: "Keys", status: "accepted" },
          { id: "as-13-sam", personId: "person-sam", position: "Drums", status: "declined" },
          { id: "as-13-caleb", personId: "person-caleb", position: "Bass", status: "pending" },
        ],
      },
      {
        id: "plan-sep-20",
        name: "Harbor Sunday",
        date: "2026-09-20",
        serviceTime: "10:00 AM",
        notes: "Baptism Sunday. Leave an extra 6 minutes after sermon for testimonies.",
        createdAt: now,
        items: [
          {
            id: "item-20-fount",
            type: "song",
            title: "Come Thou Fount",
            songId: "song-fount",
          },
          {
            id: "item-20-reasons",
            type: "song",
            title: "10,000 Reasons (Bless the Lord)",
            songId: "song-10000",
          },
          {
            id: "item-20-name",
            type: "song",
            title: "What A Beautiful Name",
            songId: "song-beautiful-name",
          },
          {
            id: "item-20-announce",
            type: "announcement",
            title: "Baptism welcome",
            body: "Invite families to the east lawn after service. No offering talk — cards in the pews.",
          },
          {
            id: "item-20-sermon",
            type: "sermon",
            title: "Buried and raised",
            body: "Romans 6. Pastor Mara.",
          },
          {
            id: "item-20-great",
            type: "song",
            title: "Great Are You Lord",
            songId: "song-great-are-you",
          },
          {
            id: "item-20-dox",
            type: "song",
            title: "Doxology",
            songId: "song-doxology",
          },
        ],
        assignments: [
          { id: "as-20-elena", personId: "person-elena", position: "Worship Leader", status: "accepted" },
          { id: "as-20-jordan", personId: "person-jordan", position: "Vocals", status: "accepted" },
          { id: "as-20-naomi", personId: "person-naomi", position: "Vocals", status: "accepted" },
          { id: "as-20-micah", personId: "person-micah", position: "Acoustic Guitar", status: "pending" },
          { id: "as-20-priya", personId: "person-priya", position: "Keys", status: "accepted" },
        ],
      },
    ],
    events: [
      {
        id: "event-league-sat",
        title: "Saturday League Match",
        date: "2026-09-13",
        time: "10:00 AM",
        location: "Away vs Northside",
        notes: "Kickoff on the north pitch. Bring pinnies.",
        createdAt: now,
        recurrence: {
          freq: "weekly",
          interval: 1,
          weekdays: [6],
          ends: { mode: "count", count: 12 },
        },
        assignments: [
          { id: "as-evt-elena", personId: "person-elena", position: "Coach", status: "accepted" },
          { id: "as-evt-jordan", personId: "person-jordan", position: "Captain", status: "pending" },
          { id: "as-evt-micah", personId: "person-micah", position: "Midfielder", status: "accepted" },
          { id: "as-evt-priya", personId: "person-priya", position: "Forward", status: "accepted" },
          { id: "as-evt-sam", personId: "person-sam", position: "Defender", status: "accepted" },
          { id: "as-evt-naomi", personId: "person-naomi", position: "Forward", status: "accepted" },
          { id: "as-evt-caleb", personId: "person-caleb", position: "Goalkeeper", status: "accepted" },
        ],
      },
    ],
    lockouts: [
      {
        id: "lock-jordan-sep13",
        personId: "person-jordan",
        userId: "user-jordan",
        start: "2026-09-12",
        end: "2026-09-14",
        note: "Out of town",
        createdAt: now,
      },
    ],
  };
}
